<a href="https://colab.research.google.com/github/kgpark88/deeplearning/blob/master/06_scikitlearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
X = np.arange(10).reshape((5, 2))
y = range(5)

In [ ]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
list(y)

[0, 1, 2, 3, 4]

In [ ]:
 X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42)

In [ ]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [ ]:
y_train

[2, 0, 3]

In [ ]:
y_test

[1, 4]

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
predictions = model.predict(X_test)

In [ ]:
predictions

array([1., 4.])